### ISSUE TITLE
Job's not cancelling and you cannot cancel it again. 

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#179]
ServerError: Server error: -32000. 'A job with status terminated cannot be terminated. It is already cancelled.'
Traceback (most recent call last):
  File "/kb/module/lib/execution_engine2/execution_engine2Server.py", line 101, in _call_method
    result = method(ctx, *params)
  File "/kb/module/lib/execution_engine2/execution_engine2Impl.py", line 767, in cancel_job
    mr.cancel_job(job_id=params["job_id"], terminated_code=params['terminated_code'] )
  File "/kb/module/lib/execution_engine2/SDKMethodRunner.py", line 452, in cancel_job
    self.get_mongo_util().cancel_job(job_id=job_id, terminated_code=terminated_code)
  File "/kb/module/lib/execution_engine2/db/MongoUtil.py", line 257, in cancel_job
    self.check_if_already_finished(j.status)
  File "/kb/module/lib/execution_engine2/db/MongoUtil.py", line 243, in check_if_already_finished
    f"A job with status {job_status} cannot be terminated. It is already cancelled."
execution_engine2.exceptions.InvalidStatusTransitionException: A job with status terminated cannot be terminated. It is already cancelled.

**Comment by bio-boris** [comment]
I'm pretty sure this is done
