### ISSUE TITLE
Fall back to finish_job_with_error if wrong object is passed into finish_job_with_success

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#187]
ERROR:root:An unhandled error was encountered
ERROR:root:Server error: -32000. "ValidationError (JobOutput:None) (Field is required: ['result'])Something was wrong with the output object"
Traceback (most recent call last):
  File "/kb/module/lib/execution_engine2/SDKMethodRunner.py", line 832, in _finish_job_with_success
    output.validate()
  File "/miniconda-latest/lib/python3.7/site-packages/mongoengine/base/document.py", line 413, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (JobOutput:None) (Field is required: ['result'])
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/kb/module/lib/execution_engine2/execution_engine2Server.py", line 101, in _call_method
    result = method(ctx, *params)
  File "/kb/module/lib/execution_engine2/execution_engine2Impl.py", line 385, in finish_job
    job_output=params.get('job_output'))
  File "/kb/module/lib/execution_engine2/SDKMethodRunner.py", line 920, in finish_job
    self._finish_job_with_success(job_id=job_id, job_output=job_output)
  File "/kb/module/lib/execution_engine2/SDKMethodRunner.py", line 850, in _finish_job_with_success
    raise Exception(str(e) + str(error_message))
Exception: ValidationError (JobOutput:None) (Field is required: ['result'])Something was wrong with the output object

**Comment by bio-boris** [comment]
Oh wait the job is correctly errored
