### ISSUE TITLE
develop fails to run jobs

### ISSUE THREAD

**Issue by MrCreosote** [kbase/execution_engine2#316]
```
Error while trying to start your app (run_app)!
-----------------------------------------------
"'SDKMethodRunner' object has no attribute 'get_workspace'"
-----------------------------------------------
Traceback (most recent call last):
  File "/kb/runtime/lib/python3.6/site-packages/biokbase-0.0.1-py3.6.egg/biokbase/narrative/jobs/appmanager.py", line 480, in _run_app_internal
    ).run_job(job_runner_inputs)
  File "/kb/runtime/lib/python3.6/site-packages/biokbase-0.0.1-py3.6.egg/biokbase/execution_engine2/execution_engine2Client.py", line 153, in run_job
    "execution_engine2.run_job", [params], self._service_ver, context
  File "/kb/runtime/lib/python3.6/site-packages/biokbase-0.0.1-py3.6.egg/biokbase/execution_engine2/baseclient.py", line 296, in call_method
    return self._call(url, service_method, args, context)
  File "/kb/runtime/lib/python3.6/site-packages/biokbase-0.0.1-py3.6.egg/biokbase/execution_engine2/baseclient.py", line 212, in _call
    raise ServerError(**err["error"])
biokbase.execution_engine2.baseclient.ServerError: Server error: -32000. "'SDKMethodRunner' object has no attribute 'get_workspace'"
Traceback (most recent call last):
  File "/kb/module/lib/execution_engine2/execution_engine2Server.py", line 101, in _call_method
    result = method(ctx, *params)
  File "/kb/module/lib/execution_engine2/execution_engine2Impl.py", line 234, in run_job
    job_id = mr.run_job(params)
  File "/kb/module/lib/execution_engine2/sdk/SDKMethodRunner.py", line 195, in run_job
    return self.get_runjob().run(params=params, as_admin=as_admin)
  File "/kb/module/lib/execution_engine2/sdk/EE2Runjob.py", line 371, in run
    return self._run(params=params, concierge_params=cp)
  File "/kb/module/lib/execution_engine2/sdk/EE2Runjob.py", line 220, in _run
    prepared = self._prepare_to_run(
  File "/kb/module/lib/execution_engine2/sdk/EE2Runjob.py", line 194, in _prepare_to_run
    self._check_ws_objects(source_objects=params.get("source_ws_objects"))
  File "/kb/module/lib/execution_engine2/sdk/EE2Runjob.py", line 136, in _check_ws_objects
    info = self.sdkmr.get_workspace().get_object_info3(
AttributeError: 'SDKMethodRunner' object has no attribute 'get_workspace'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kb/runtime/lib/python3.6/site-packages/biokbase-0.0.1-py3.6.egg/biokbase/narrative/jobs/appmanager.py", line 357, in run_app
    app_id, params, tag, version, cell_id, run_id, dry_run
  File "/kb/runtime/lib/python3.6/site-packages/biokbase-0.0.1-py3.6.egg/biokbase/narrative/jobs/appmanager.py", line 484, in _run_app_internal
    raise transform_job_exception(e)
biokbase.narrative.exception_util.NarrativeException: "'SDKMethodRunner' object has no attribute 'get_workspace'"
```

**Comment by MrCreosote** [comment]
Fixed by https://github.com/kbase/execution_engine2/pull/317
