### ISSUE TITLE
When a request to status doesn't include an `id` field, the service responds with an HTML 500 page

### ISSUE THREAD

**Issue by MrCreosote** [kbase/execution_engine2#494]
I would at least expect a JSON response

Most other services also don't require an id (which is bad IMO), not sure why it's required here given it's also SDK compiled.

```
curl -d '{"params":[],"method":"execution_engine2.status"}' https://ci.kbase.us/services/ee2
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

**Comment by bio-boris** [comment]
```
11/18/2024 5:06:36 PMTraceback (most recent call last):
11/18/2024 5:06:36 PM  File "/miniconda-latest/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 55, in handle
11/18/2024 5:06:36 PM    self.handle_request(listener_name, req, client, addr)
11/18/2024 5:06:36 PM  File "/miniconda-latest/lib/python3.10/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
11/18/2024 5:06:36 PM    super().handle_request(listener_name, req, sock, addr)
11/18/2024 5:06:36 PM  File "/miniconda-latest/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
11/18/2024 5:06:36 PM    respiter = self.wsgi(environ, resp.start_response)
11/18/2024 5:06:36 PM  File "/kb/module/lib/execution_engine2/execution_engine2Server.py", line 599, in __call__
11/18/2024 5:06:36 PM    ctx["call_id"] = req["id"]
11/18/2024 5:06:36 PMKeyError: 'id'
```

**Comment by bio-boris** [comment]
We suspect that all python services require an ID

**Comment by MrCreosote** [comment]
The bigger issue for me here is why it's not returning a JSON response with the stacktrace

**Comment by MrCreosote** [comment]
> We suspect that all python services require an ID

if this is true, they should respond with a reasonable error message, which means updating kb_sdk, which means getting kb_sdk_plus in a position where it can be developed
